language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t docker-react-dev -f Dockerfile.dev .        
script:
        - docker run -e CI=true docker-react-dev npm run test        
deploy: 
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-us-east-2-673521144972"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWD_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
