# BUILD PHASE
FROM node:16-alpine as builder

WORKDIR /home/node/app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# RUN PHASE

FROM nginx

COPY --from=builder /home/node/app/build /usr/share/nginx/html

# nginx starts the binary by default
